# Generated by Django 5.0.3 on 2024-03-06 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forename", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("imsi", models.CharField(max_length=15, unique=True)),
                ("terminal_type", models.CharField(max_length=50)),
                ("subscription_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_type", models.CharField(max_length=50)),
                ("session_duration", models.DurationField()),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matsecom.subscriber",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_data_volume", models.PositiveIntegerField()),
                ("total_voice_minutes", models.PositiveIntegerField()),
                (
                    "applied_charges",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matsecom.subscriber",
                    ),
                ),
            ],
        ),
    ]
