# Generated by Django 5.0.3 on 2024-03-06 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matsecom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("VC", "Voice call"),
                            ("BN", "Browsing and social networking"),
                            ("AD", "App download"),
                            ("AV", "Adaptive HD video"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "ran_technologies",
                    models.CharField(
                        choices=[("2G", "2G"), ("3G4G", "3G or 4G")], max_length=5
                    ),
                ),
                (
                    "required_data_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("GS", "GreenMobil S"),
                            ("GM", "GreenMobil M"),
                            ("GL", "GreenMobil L"),
                        ],
                        max_length=50,
                    ),
                ),
                ("basic_fee", models.DecimalField(decimal_places=2, max_digits=5)),
                ("minutes_included", models.PositiveIntegerField()),
                (
                    "price_per_extra_minute",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("data_volume_3g_4g", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("2G", "2G (GSM)"),
                            ("3G", "3G (HSPA)"),
                            ("4G", "4G (LTE)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "maximum_throughput",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("voice_call_support", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ThroughputPercentage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signal_quality",
                    models.CharField(
                        choices=[
                            ("G", "Good"),
                            ("M", "Medium"),
                            ("L", "Low"),
                            ("N", "N/A"),
                        ],
                        max_length=2,
                    ),
                ),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.RemoveField(
            model_name="servicesession",
            name="subscriber",
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="subscription_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="matsecom.subscription",
            ),
        ),
        migrations.CreateModel(
            name="Terminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("default_to_4g", models.BooleanField(default=False)),
                (
                    "supported_technologies",
                    models.ManyToManyField(to="matsecom.technology"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="terminal_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="matsecom.terminal",
            ),
        ),
        migrations.AddField(
            model_name="technology",
            name="achievable_throughput_percentages",
            field=models.ManyToManyField(to="matsecom.throughputpercentage"),
        ),
        migrations.DeleteModel(
            name="Invoice",
        ),
        migrations.DeleteModel(
            name="ServiceSession",
        ),
    ]
