# Generated by Django 5.0.3 on 2024-03-06 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matsecom", "0003_remove_terminal_default_to_4g_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("duration", models.PositiveIntegerField()),
                ("data_volume", models.PositiveIntegerField()),
                ("call_minutes", models.PositiveIntegerField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matsecom.service",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matsecom.subscriber",
                    ),
                ),
            ],
        ),
    ]
