# Generated by Django 5.0.3 on 2024-03-07 09:47

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matsecom", "0004_session_paid_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="forename",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="imsi",
            field=encrypted_model_fields.fields.EncryptedCharField(unique=True),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="surname",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
