# Generated by Django 5.0.3 on 2024-03-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matsecom", "0005_alter_subscriber_forename_alter_subscriber_imsi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="price_per_extra_minute",
            field=models.PositiveIntegerField(),
        ),
    ]
