# Generated by Django 5.0.3 on 2024-03-07 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matsecom", "0007_alter_subscription_basic_fee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="duration",
            new_name="charges",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="service",
        ),
        migrations.AlterField(
            model_name="session",
            name="subscriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="matsecom.subscriber",
            ),
        ),
    ]
