# Generated by Django 5.0.3 on 2024-03-07 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matsecom", "0009_rename_call_minutes_session_call_seconds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="subscription_type",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="matsecom.subscription",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="terminal_type",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="matsecom.terminal",
            ),
            preserve_default=False,
        ),
    ]
