# Generated by Django 5.0.3 on 2024-03-07 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matsecom", "0010_alter_subscriber_subscription_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="matsecom.service"
            ),
        ),
    ]
