# Generated by Django 5.0.3 on 2024-03-07 22:32

import django.core.validators
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matsecom", "0011_alter_session_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="duration",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(2500000),
                    django.core.validators.MinValueValidator(1),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="subscriber",
            name="imsi",
            field=encrypted_model_fields.fields.EncryptedPositiveIntegerField(
                unique=True,
                validators=[
                    django.core.validators.MaxValueValidator(999999999999999),
                    django.core.validators.MinValueValidator(100000000000000),
                ],
            ),
        ),
    ]
