# Generated by Django 5.0.3 on 2024-03-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matsecom", "0014_alter_subscriber_imsi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriber",
            name="imsi",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
